### ISSUE TITLE
Missing a script link to  <script src="/socket.io/socket.io.js"></script> in index.html

### ISSUE THREAD

**Issue by RachBLondon** [fcscripters/Devs-In-The-Detail#27]
https://github.com/fcscripters/Devs-In-The-Detail/blob/master/answers.html#L20

This should go   above  var socket = io();

**Comment by sohilpandya** [comment]
strange as our socket is not breaking without it!

**Comment by RachBLondon** [comment]
Ok fair enough, if it does start to play up it might be worth a look
