### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by jefferson-jefferson** [fcscripters/Devs-In-The-Detail#6]
@sohilpandya @Conorc1000 @tormod17 @thegsi. Hi guys can you make the README.md more readable please. i.e bullet point for step by step processes, sub headings to separate content.

**Comment by rjmk** [comment]
Despite readability issues, I'm loving the tutorial nature of this README! :star2:

**Comment by rub1e** [comment]
Some markdown would be nice - esp for code snippets

https://guides.github.com/features/mastering-markdown/

**Comment by jefferson-jefferson** [comment]
This issue has been resolved.
